# Generated by Django 4.0.5 on 2022-06-15 04:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('addres', models.TextField(max_length=200)),
                ('categories', models.CharField(choices=[('marketing', 'Marketing'), ('customer service', 'Customer service'), ('human resource', 'Human resource'), ('project management', 'Project management'), ('business devlopment', 'Business devlopment'), ('sales & communication', 'Seles & communication'), ('teaching & education', 'Teaching & education'), ('information technology', 'Information technology')], max_length=100)),
                ('job_description', models.TextField(max_length=200)),
                ('experience', models.CharField(max_length=50)),
                ('slot', models.IntegerField()),
                ('type', models.CharField(choices=[('part-time', 'Part-time'), ('full-time', 'full-time')], max_length=25)),
                ('city', models.CharField(max_length=20)),
                ('time', models.DateField(default=datetime.date.today)),
                ('HR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=30)),
                ('Bod', models.DateField(max_length=20)),
                ('mobile', models.CharField(max_length=15)),
                ('resume', models.FileField(upload_to='resume')),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.jobpost')),
            ],
        ),
    ]
