# Generated by Django 4.0.5 on 2022-06-16 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_user_managers_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='myapp.jobpost'),
        ),
    ]
